/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mashud786 (https://sketchfab.com/Mashud786)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dark-orb-1f2a74fe4150409d879a6c00c11eeb1c
title: Dark Orb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function DarkOrb() {
  const ref = useRef();
  document.addEventListener("mousemove", onDocumentMouseMove);
  let mouseX = 0;
  let mouseY = 0;

  let targetX = 0;
  let targetY = 0;

  const windowHalfX = window.innerWidth / 2;
  const windowHalfY = window.innerWidth / 2;

  function onDocumentMouseMove(event) {
    mouseX = event.clientX - windowHalfX;
    mouseY = event.clientY - windowHalfY;
  }
  useFrame((state) => {
    targetX = mouseX * 0.001;
    targetY = mouseY * 0.001;

    const t = state.clock.getElapsedTime() + 5 * 10000;
    ref.current.rotation.y = 0.2 * t;

    ref.current.rotation.y += 0.5 * (targetX - ref.current.rotation.y);
    ref.current.rotation.x += 0.5 * (targetY - ref.current.rotation.x);
    ref.current.rotation.x += -0.5 * (targetY - ref.current.rotation.x);
  });

  const { nodes, materials } = useGLTF("/dark_orb/scene-transformed.glb");
  return (
    <group ref={ref} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Hedra001_17_-_Old_Copper_#1_0"].geometry}
              material={nodes["Hedra001_17_-_Old_Copper_#1_0"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Hedra001_17_-_Old_Copper_#1_0_1"].geometry}
              material={nodes["Hedra001_17_-_Old_Copper_#1_0_1"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Hedra001_17_-_Old_Copper_#1_0_2"].geometry}
              material={nodes["Hedra001_17_-_Old_Copper_#1_0_2"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Hedra001_17_-_Old_Copper_#1_0_3"].geometry}
              material={nodes["Hedra001_17_-_Old_Copper_#1_0_3"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Hedra001_17_-_Old_Copper_#1_0_4"].geometry}
              material={nodes["Hedra001_17_-_Old_Copper_#1_0_4"].material}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Sphere001_17_-_Old_Copper_#1_0"].geometry}
              material={materials["17_-_Old_Copper_1_0"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dark_orb/scene-transformed.glb");
